### ISSUE TITLE
Pattern Terminal Autofilling Sag Mill Recipes Crash

### ISSUE THREAD

**Issue by KrakenG7** [p455w0rd/JustEnoughEnergistics#11]
Mod Version 1.0.7
Enigmatica 2 Expert version 1.66c

The client crashes when attempting to autofill any sag mill processing recipe

**Comment by Frikkle** [comment]
This has also been reported in the Enigmatica 2 Expert Issue tracker; for reference: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1296

The bug is reproducable, crash log can be found the referenced issue.

I haven't had time to try and reproduce this in a minimum setup of AE2, JEE and EnderIO. Will try to do so tonight and post my results here.

**Comment by KrakenG7** [comment]
oh yea, I forgot the report... Here it is :)

https://pastebin.com/c2JDBq7d

**Comment by tyler489** [comment]
This only applies to recipys that have a grinding ball.

**Comment by p455w0rd** [comment]
`TheRealp455w0rd#7817` on discord if anyone would like to test a dev version for me
